name: Scan with Detekt

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Detekt
        uses: burrunan/gradle-cache-action@v1
        continue-on-error: true
        with:
          job-id: jdk11-v3
          # detekt has intermittent issues when parallel
          arguments: --no-parallel clean detekt
          gradle-dependencies-cache-key: |
            **/*.gradle.kts
            **/gradle.properties
          properties: |
            kotlin.parallel.tasks.in.project=true
          concurrent: true

      # Upload results to GitHub repository using the upload-sarif action
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: build/reports/detekt/detekt.sarif
